name: Build SwitchGuiLibrary
on: [push]
jobs:
  SwitchGuiLibrary:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive
        
    - name: Building SwitchGuiLibrary
      run: |
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: SwitchGuiLibrary
        path: SwitchGuiLibrary.nro
